export interface ScheduleOfValue {
  id: string
  name: string
  type: "Initial" | "Owner" | "Internal"
  status: "Pending" | "Submitted" | "Approved" | "Rejected"
  submittedDate: string
  totalAmount: number
}

export interface SOVLineItem {
  id: string
  code: string
  description: string
  currentAmount: number
  adjustmentAmount: number
  adjustedAmount: number
  currentCommittedAmount: number
  billedToDateAmount: number
  category: string
}

export const ScheduleOfValuesData: ScheduleOfValue[] = [
  {
    id: "1",
    name: "Initial",
    type: "Initial",
    status: "Pending",
    submittedDate: "",
    totalAmount: 321605.24,
  },
  {
    id: "2",
    name: "Final CO",
    type: "Owner",
    status: "Submitted",
    submittedDate: "1/17/2024",
    totalAmount: -4668.58,
  },
  {
    id: "3",
    name: "CO #08",
    type: "Owner",
    status: "Submitted",
    submittedDate: "8/28/2023",
    totalAmount: 0.0,
  },
  {
    id: "4",
    name: "CO #07",
    type: "Owner",
    status: "Submitted",
    submittedDate: "4/3/2023",
    totalAmount: 0.0,
  },
  {
    id: "5",
    name: "Exterior Upgrades",
    type: "Owner",
    status: "Submitted",
    submittedDate: "7/11/2022",
    totalAmount: 4945.0,
  },
  {
    id: "6",
    name: "PCO #05",
    type: "Owner",
    status: "Submitted",
    submittedDate: "5/26/2022",
    totalAmount: 630.18,
  },
  {
    id: "7",
    name: "Stucco and Landscape Lighting",
    type: "Owner",
    status: "Submitted",
    submittedDate: "4/29/2022",
    totalAmount: 0.0,
  },
  {
    id: "8",
    name: "3/24/2022 9:27:10 AM",
    type: "Owner",
    status: "Submitted",
    submittedDate: "3/24/2022",
    totalAmount: 2425.21,
  },
  {
    id: "9",
    name: "Lighting Control",
    type: "Owner",
    status: "Submitted",
    submittedDate: "3/16/2022",
    totalAmount: 0.0,
  },
  {
    id: "10",
    name: "Remove 50 Items",
    type: "Internal",
    status: "Submitted",
    submittedDate: "2/9/2022",
    totalAmount: 0.0,
  },
  {
    id: "11",
    name: "12/7/2021 6:10:51 PM",
    type: "Initial",
    status: "Submitted",
    submittedDate: "12/7/2021",
    totalAmount: 72938.4,
  },
]

export const SOVLineItemsData: SOVLineItem[] = [
  {
    id: "1",
    code: "02-000",
    description: "Demo & Framing",
    currentAmount: 3600.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 3600.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Demolition",
  },
  {
    id: "2",
    code: "02-500",
    description: "Landscaping",
    currentAmount: 0.0,
    adjustmentAmount: 4945.0,
    adjustedAmount: 4945.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Landscaping",
  },
  {
    id: "3",
    code: "04-000",
    description: "Stucco",
    currentAmount: 8529.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 8529.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Masonry",
  },
  {
    id: "4",
    code: "06-110",
    description: "Wood Framing - Non-Structural",
    currentAmount: 4400.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 4400.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Rough Carpentry",
  },
  {
    id: "5",
    code: "06-200",
    description: "Base & Casing & Doors",
    currentAmount: 9120.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 9120.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Rough Carpentry",
  },
  {
    id: "6",
    code: "07-130",
    description: "Insulation",
    currentAmount: 500.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 500.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Insulation",
  },
  {
    id: "7",
    code: "08-100",
    description: "Interior Doors",
    currentAmount: 1950.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 1950.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Doors",
  },
  {
    id: "8",
    code: "08-110",
    description: "Exterior Doors",
    currentAmount: 11600.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 11600.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Doors",
  },
  {
    id: "9",
    code: "08-120",
    description: "Door Hardware",
    currentAmount: 950.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 950.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Doors",
  },
  {
    id: "10",
    code: "08-200",
    description: "Windows",
    currentAmount: 17935.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 17935.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Windows & Glazing",
  },
  {
    id: "11",
    code: "08-210",
    description: "Interior Glazing",
    currentAmount: 28645.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 28645.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Windows & Glazing",
  },
  {
    id: "12",
    code: "09-100",
    description: "Drywall and Tile",
    currentAmount: 6040.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 6040.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Drywall",
  },
  {
    id: "13",
    code: "09-220",
    description: "Tile & Stone Materials",
    currentAmount: 2600.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 2600.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Tile & Stone",
  },
  {
    id: "14",
    code: "09-225",
    description: "Tile & Stone Labor",
    currentAmount: 4440.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 4440.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Tile & Stone",
  },
  {
    id: "15",
    code: "09-230",
    description: "Shower Pans",
    currentAmount: 2000.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 2000.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Tile & Stone",
  },
  {
    id: "16",
    code: "10-100",
    description: "Specialties",
    currentAmount: 3222.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 3222.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Specialties",
  },
  {
    id: "17",
    code: "12-100",
    description: "Cabinets, Countertops and Specialties",
    currentAmount: 16680.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 16680.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Cabinets and Casework",
  },
  {
    id: "18",
    code: "12-110",
    description: "Cabinet Install",
    currentAmount: 3240.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 3240.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Cabinets and Casework",
  },
  {
    id: "19",
    code: "12-130",
    description: "Countertops",
    currentAmount: 37275.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 37275.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Countertops",
  },
  {
    id: "20",
    code: "15-100",
    description: "Rough In Plumbing",
    currentAmount: 12000.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 12000.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Plumbing",
  },
  {
    id: "21",
    code: "15-110",
    description: "Plumbing Trim Install",
    currentAmount: 1200.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 1200.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Plumbing",
  },
  {
    id: "22",
    code: "15-120",
    description: "Plumbing Fixture Package",
    currentAmount: 11414.0,
    adjustmentAmount: 0.0,
    adjustedAmount: 11414.0,
    currentCommittedAmount: 0.0,
    billedToDateAmount: 0.0,
    category: "Plumbing",
  },
]
