export interface BudgetAdjustment {
  id: string
  name: string
  type: "Owner" | "Internal" | "Initial"
  status: "Submitted" | "Pending" | "Approved" | "Rejected"
  fee: number
  submittedDate: string
}

export const BudgetAdjustmentsData: BudgetAdjustment[] = [
  {
    id: "1",
    name: "CO #10",
    type: "Owner",
    status: "Submitted",
    fee: -2434.76,
    submittedDate: "1/25/2024",
  },
  {
    id: "2",
    name: "CO #09",
    type: "Owner",
    status: "Submitted",
    fee: -4668.58,
    submittedDate: "1/25/2024",
  },
  {
    id: "3",
    name: "Final Adjustment",
    type: "Internal",
    status: "Submitted",
    fee: 2640.53,
    submittedDate: "1/29/2024",
  },
  {
    id: "4",
    name: "Final CO",
    type: "Owner",
    status: "Submitted",
    fee: -4668.58,
    submittedDate: "1/17/2024",
  },
  {
    id: "5",
    name: "10.2.23 Writedown",
    type: "Internal",
    status: "Submitted",
    fee: -4000.0,
    submittedDate: "10/2/2023",
  },
  {
    id: "6",
    name: "CO #08",
    type: "Owner",
    status: "Submitted",
    fee: 0.0,
    submittedDate: "8/28/2023",
  },
  {
    id: "7",
    name: "Cost Control Budget (4/24/2023) 17-150",
    type: "Internal",
    status: "Submitted",
    fee: 0.0,
    submittedDate: "4/24/2023",
  },
  {
    id: "8",
    name: "CO #07",
    type: "Owner",
    status: "Submitted",
    fee: 0.0,
    submittedDate: "4/3/2023",
  },
  {
    id: "9",
    name: "Cost Control Budget (10/3/2022) 09-120",
    type: "Internal",
    status: "Submitted",
    fee: 0.0,
    submittedDate: "10/3/2022",
  },
  {
    id: "10",
    name: "Writedown per KR.07.20",
    type: "Internal",
    status: "Submitted",
    fee: -11905.79,
    submittedDate: "7/20/2022",
  },
  {
    id: "11",
    name: "Exterior Upgrades",
    type: "Owner",
    status: "Submitted",
    fee: 645.0,
    submittedDate: "7/11/2022",
  },
  {
    id: "12",
    name: "PCO #05",
    type: "Owner",
    status: "Submitted",
    fee: 630.18,
    submittedDate: "5/26/2022",
  },
  {
    id: "13",
    name: "Lights from Stucco",
    type: "Internal",
    status: "Submitted",
    fee: 0.0,
    submittedDate: "4/29/2022",
  },
  {
    id: "14",
    name: "Remove Stucco and Add landscape lighting",
    type: "Owner",
    status: "Submitted",
    fee: 0.0,
    submittedDate: "4/29/2022",
  },
  {
    id: "15",
    name: "Lighting Additions",
    type: "Owner",
    status: "Submitted",
    fee: 2425.21,
    submittedDate: "3/24/2022",
  },
  {
    id: "16",
    name: "Lighting Control",
    type: "Owner",
    status: "Submitted",
    fee: 0.0,
    submittedDate: "3/16/2022",
  },
  {
    id: "17",
    name: "Drywall",
    type: "Internal",
    status: "Submitted",
    fee: 0.0,
    submittedDate: "3/4/2022",
  },
  {
    id: "18",
    name: "Cost Control Budget (2/1/2022) 16-120",
    type: "Internal",
    status: "Submitted",
    fee: 0.0,
    submittedDate: "2/1/2022",
  },
  {
    id: "19",
    name: "Cost Control Budget (2/1/2022) 16-110",
    type: "Internal",
    status: "Submitted",
    fee: 0.0,
    submittedDate: "2/1/2022",
  },
  {
    id: "20",
    name: "Cost Control Budget (1/11/2022) 06-200",
    type: "Internal",
    status: "Submitted",
    fee: 0.0,
    submittedDate: "1/11/2022",
  },
  {
    id: "21",
    name: "Initial Budget created from Estimate",
    type: "Initial",
    status: "Submitted",
    fee: 72938.4,
    submittedDate: "12/7/2021",
  },
  {
    id: "22",
    name: "Initial",
    type: "Owner",
    status: "Pending",
    fee: 0.0,
    submittedDate: "",
  },
]
