export interface SOVItem {
  itemNumber: string
  description: string
  scheduledValue: number
  workCompletedPrevious: number
  workCompletedThisPeriod: number
  materialsStored: number
  retainage: number
}

export const SOVData: SOVItem[] = [
  {
    itemNumber: "01-000",
    description: "Demo & Framing",
    scheduledValue: 3800.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "01-100",
    description: "Concrete",
    scheduledValue: 4200.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "01-200",
    description: "Masonry",
    scheduledValue: 15768.0,
    workCompletedPrevious: -4.97,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "06-100",
    description: "Wood Framing - Non-Structural",
    scheduledValue: 5400.0,
    workCompletedPrevious: 1800,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "06-200",
    description: "Finish Carpentry & Doors",
    scheduledValue: 4200.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "07-100",
    description: "Insulation",
    scheduledValue: 500.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "08-100",
    description: "Interior Doors",
    scheduledValue: 1900.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "08-200",
    description: "Exterior Doors",
    scheduledValue: 980.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "08-300",
    description: "Door Hardware",
    scheduledValue: 850.0,
    workCompletedPrevious: -260,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "08-400",
    description: "Windows",
    scheduledValue: 19344.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "08-500",
    description: "Interior Glazing",
    scheduledValue: 58444.0,
    workCompletedPrevious: -16.79,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "09-100",
    description: "Drywall and Tile",
    scheduledValue: 5340.0,
    workCompletedPrevious: 1800,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "09-200",
    description: "Flooring - Hardwood",
    scheduledValue: 7200.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "09-210",
    description: "Tile & Stone Labor",
    scheduledValue: 4440.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "09-220",
    description: "Shower Pan",
    scheduledValue: 2700.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "09-300",
    description: "Painting",
    scheduledValue: 3600.0,
    workCompletedPrevious: -2778,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "15-100",
    description: "Cabinets, Countertops and Specialties",
    scheduledValue: 56488.0,
    workCompletedPrevious: 5344,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "15-200",
    description: "Cabinet Install",
    scheduledValue: 5136.0,
    workCompletedPrevious: -1800,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "15-300",
    description: "Appliances",
    scheduledValue: 3300.0,
    workCompletedPrevious: 1800,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "15-400",
    description: "Rough-In Plumbing",
    scheduledValue: 32000.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "15-500",
    description: "Plumbing Trim Install",
    scheduledValue: 1200.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "16-100",
    description: "Electrical Rough-In Package",
    scheduledValue: 8400.0,
    workCompletedPrevious: -900,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "16-200",
    description: "HVAC Rough-In",
    scheduledValue: 2400.0,
    workCompletedPrevious: 631.38,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "16-300",
    description: "HVAC Trim",
    scheduledValue: 300.0,
    workCompletedPrevious: -300,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "16-400",
    description: "Electrical Trim",
    scheduledValue: 1800.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "16-500",
    description: "Electrical Trim Install",
    scheduledValue: 2200.0,
    workCompletedPrevious: 2.82,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "16-600",
    description: "Electrical Fixture Install",
    scheduledValue: 55100.0,
    workCompletedPrevious: 51198.25,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "17-100",
    description: "Misc",
    scheduledValue: 600.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "17-200",
    description: "Misc Jobsite Overhead",
    scheduledValue: 600.0,
    workCompletedPrevious: -90,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "17-300",
    description: "Cleaning",
    scheduledValue: 1700.0,
    workCompletedPrevious: -200,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "17-400",
    description: "Permits and Pest Protection",
    scheduledValue: 1200.0,
    workCompletedPrevious: -140,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "17-500",
    description: "Plans",
    scheduledValue: 1300.0,
    workCompletedPrevious: 1300,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "17-600",
    description: "Permits",
    scheduledValue: 3000.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "18-100",
    description: "Contingency",
    scheduledValue: 6000.0,
    workCompletedPrevious: -1500,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "19-100",
    description: "Insurance",
    scheduledValue: 2300.0,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "19-200",
    description: "Supervision",
    scheduledValue: 1765.15,
    workCompletedPrevious: 0,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
  {
    itemNumber: "11-400",
    description: "Management Fee",
    scheduledValue: 72398.4,
    workCompletedPrevious: -6888.81,
    workCompletedThisPeriod: 0,
    materialsStored: 0,
    retainage: 0,
  },
]
